AWSTemplateFormatVersion: '2010-09-09'
Description: 'lab-s3-glue-v1.0.0'

Parameters:

  S3BucketNameGlue:
    Type: String
    Description: The name for the S3 bucket - must be unique across all of AWS (3-63 lowercase letters,numbers or character(_,-))
    Default: "default"
    AllowedPattern: '^[a-zA-Z0-9][a-zA-Z0-9_-]{5,40}$'
    ConstraintDescription: 3-63 characters; must contain only lowercase letters or numbers

  S3BucketNameAthena:
    Type: String
    Description: The name for the S3 bucket - must be unique across all of AWS (3-63 lowercase letters,numbers or character(_,-))
    Default: "default"
    AllowedPattern: '^[a-zA-Z0-9][a-zA-Z0-9_-]{5,40}$'
    ConstraintDescription: 3-63 characters; must contain only lowercase letters or numbers
    

Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"
 
  MyDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: "glue-database"
 
  MyS3BucketGlue:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketNameGlue
      
  MyS3BucketAthena:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketNameAthena

  MyCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: "glue-crawler"
      Role: !GetAtt MyRole.Arn
      DatabaseName: !Ref MyDatabase
      TablePrefix: "crawler-s3-"
      Targets:
        S3Targets:
          - Path: !Ref MyS3BucketGlue
